#!/sbin/sh
setprop service.adb.root 1
if [ -e /sbin/bootrec-device ]
then
  /sbin/bootrec-device
fi

if [ -s /dev/keycheck1 -o -e /cache/recovery/boot ] || [ -s /dev/keycheck2 ]
then
  echo 0 > /sys/class/android_usb/android0/enable
  echo 0fce > /sys/class/android_usb/android0/idVendor 
  echo 614f > /sys/class/android_usb/android0/idProduct
  echo "mass_storage,adb" > /sys/class/android_usb/android0/functions
  echo 1 > /sys/class/android_usb/android0/enable
  stop adbd
  umount -l /system
  umount -l /data
  mount -o remount,rw rootfs /
  umount -l /system
  umount -l /data
  umount -l /mnt/sdcard
  rm -r /sdcard
  rm -r /not/sdcard
  mkdir /sdcard
  mkdir /tmp
  rm /etc
  mkdir /etc
  cp /recovery.fstab /etc/recovery.fstab
  mount /dev/block/mmcblk0p1 /sdcard
  if [ -s /dev/keycheck2 ]
  then
    chmod 777 /res/aromafm
    if [ ! -s /sdcard/aromafm_data.zip ]
    then
      cp /res/aromafm_data.zip /sdcard/aromafm_data.zip
    fi
    if [ ! -s /sdcard/aromafm_data.zip.cfg ]
    then
      cp /res/aromafm_data.zip.cfg /sdcard/aromafm_data.zip.cfg
    fi
    mount -o rw -t yaffs2 /dev/block/mtdblock0 /system
    mount -o rw -t yaffs2 /dev/block/mtdblock1 /data
    /res/aromafm 1 0 /sdcard/aromafm_data.zip
    reboot
  elif [ -s /dev/keycheck1 -o -e /cache/recovery/boot ]
  then
    rm /cache/recovery/boot
    umount -l /cache
    /sbin/recovery&
  fi  
fi
    
/system/bin/chargemon
#continue booting

